=pod

=head1 NAME

l10n-maker - Translate dictionary generator for Movable Type.

=head1 DESCRIPTION

this script generates and updates translate dictyonary from source codes of
Movable Type and it's plugins.

=head1 SYNOPSIS

$ l10nmaker --component=core --output=ja.pm

=head1 OPTIONS

=over 4

=item * component

specify the component name to make translate file.

=item * translated

specify the l10n file that already exists

=item * laguage

langtag of target language of translating

=item * steal-from-core ( optional )

if it's true, and the phrase was found in MT core translate dictionary, include
it to the new lexicon.

=item * format ( optional )

output format

=item * new-phrases-only|n ( optional )

output unknown phrases only

=item * footprint ( optional: default is true )

flag to print comment that says which file the phrases come from. if you don't
like it, --no-footprint to stop it.

=item * no-unused ( optional )

by default, script outputs the phrases that already translated but can't find
in the source codes, at the end of lexicon. if this option is enabled, stop that.

=item * output ( optional )

specify the output file to generate.
if no output file was passed, script prints out the dictionary to STDOUT.

=item * verbose ( optional )

prints the details what this script is doing to STDERR.

=item * help

display this help.

=back

=head1 PREREQUEST

cd (MT_HOME) or set MT_HOME evnironment variable to the absolute path
of root directory of MT.


=cut

